### ISSUE TITLE
Create new branch called tetrahedron to work on tetrahedron.js and tetrahedron.css

### ISSUE THREAD

**Issue by muktoakash** [HPQC-LABS/HPQC#121]

**Comment by muktoakash** [comment]
Github does not allow me to create a new branch on this repo.

**Comment by ndattani** [comment]
@muktoakash It would be better to make a fork than a branch. 

Almost 4 years ago we created the branch called "Mukto" (https://github.com/HPQC-LABS/HPQC/tree/Mukto) for your contributions, but we now have 179 members in the HPQC-LABS organization, and based on various experiences over the recent years, it turns out that it would be better for this type of individual contribution to be made via a fork rather than a branch. The entire code for the "tetrahedron calculator" was also merged into the main fork from Sichao's fork. 

If there's a group of people working on a feature at the same time, it might make sense for all of them to contribute to the same "branch" rather than to individual "forks"; and for computing software it can be useful to have multiple branches so that users can choose to run something such as :
```
git clone -b quadruple-precision <repository> 
git clone -b double-precision <repository> 
```
depending on which type of calculation they want to do, but this is not the case with the tetrahedron calculator.

**Comment by muktoakash** [comment]
@ndattani thank you for the reply. I did consider using the "Mukto" branch to do the work, but since it's a single feature which may have more contributors, it did not seem right to use a branch with a username on it.

Quite interesting that you found forks to be the better solution in such cases. That's a peculiar organizational workflow, but I can work with that. However, it will take away a lot of your control on the contributions until I put in a PR. Also, since the PR will probably be at the end, you will not get to follow any intermediate work, and will have to carefully review the entire code and deal with conflicts, if there are any.

**Comment by ndattani** [comment]
@muktoakash with almost every GitHub repository, you would have to make a fork to contribute, because you can't make your own branches.  

- As for control on the contributions, there might be some limitations if your fork restricts others from contributing to it (for example), but for the planned aesthetic changes to the tetrahedron.html page, I wasn't anticipating the need to mix your contributions with contributions of my own.
- As for making the PR at the end, you can make a "draft PR" or a full PR at any time, then continue working on it. This way you can get comments on the code gradually.
- As for dealing with merge conflicts, this would be necessary whether the contributions are made in a fork or a branch.

**Comment by ndattani** [comment]
@muktoakash I see that you made a fork in the HPQC-LABS organization. Basically, each person has their own fork, as you can see here: https://github.com/HPQC-LABS/HPQC/forks?page=1. The new fork is a bit like the HPQC-1 and HPQC-2 that you pointed out earlier. By default when making a fork, the fork is "owned" by the user making the fork, but if the user switches the owner to HPQC-LABS, then the fork is created in the HPQC-LABS organization. I'll see if I can make it so that people can't do that anymore.

**Comment by ndattani** [comment]
@muktoakash it looks like I can't prevent organization members from forking into the organization: https://stackoverflow.com/a/67695052/1271772, so I can't prevent us from getting a bunch of new repositories such as HPQC-1, HPQC-2, HPQC-Tetrahedron. Perhaps I just need to make the rules clear somewhere that forks ought to be made in one's own account (along with the rule that I have that people ought to only make one pull request at a time, which is a rule that I had to make because too many people that are new to GitHub, seemed to be making new pull requests whenever there was a comment requesting additions or changes, rather than just "updating" the existing pull request).

**Comment by ndattani** [comment]
Actually I think I got the settings working so that users can no longer make HPQC-1, HPQC-2, etc. in the organization's main front page. Can you try to fork the repository now, and see if it says "insufficient permission" next to HPQC-LABS @muktoakash? This is what I see in the red box below, for another organization, but I need someone to test it for HPQC-LABS:

![image](https://github.com/HPQC-LABS/HPQC/assets/1163013/695c7464-374d-4bb1-aa49-e8127b9789d0)

**Comment by muktoakash** [comment]
It seems to have worked: 
![image](https://github.com/HPQC-LABS/HPQC/assets/73410983/bf69467c-4744-400e-a91b-576992020863)

You should really allow branching for within organization work. Typically forking is reserved to external people who want to contribute, and branching is for internal work.

**Comment by ndattani** [comment]
> "You should really allow branching for within organization work. Typically forking is reserved to external people who want to contribute, and branching is for internal work."

Branching is for internal work, but it is not true that forking is reserved for external people who want to contribute. Even within an organization, there's a lot of pros and cons for using forks and a lot of pros and cons for using branches.  

I allowed organization members to make branches in this repository until at least August 2022. Even now you can see some of the consequences of that:

![image](https://github.com/HPQC-LABS/HPQC/assets/1163013/3f8ccf36-d1f0-4dcc-bbd8-a1c8aa13154c).
